# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12NbiDKHP-1UfobwROYZW7mdGzGcBxuE1
"""

# Interpolate dates between two dates !

from datetime import date
d0 = date(2017, 8, 18)
d1 = date(2017, 10, 26)
delta = d1 - d0
print(delta.days)

from datetime import datetime, timedelta

def date_range(start, end):
    delta = end - start  # as timedelta
    days = [start + timedelta(days=i) for i in range(delta.days + 1)]
    return days

start_date = datetime(2008, 8, 1)
end_date = datetime(2008, 8, 3)
    
print(date_range(start_date, end_date))

from datetime import date, timedelta

sdate = date(2008, 9, 12)   # start date   
edate = date(2008, 9, 15)   # end date   

delta = edate - sdate       # as timedelta

for i in range(delta.days + 1):
    day = sdate + timedelta(days=i)
    print(day)